(ns java-gem.core-test
  (:use clojure.test
        java-gem.core))

(deftest gemify-version-test
  (is (= "simpletext" (gemify-version "simpletext")))
  (is (= "1.2.3.dotted" (gemify-version "1.2.3.dotted")))
  (is (= "1.2.3.dashed" (gemify-version "1.2.3-dashed"))))

(deftest parse-args-test
  (is (= {:group "group", :name "name",
          :output ".", :repository nil, :version "1.0"}
         (parse-args ["-g" "group" "-n" "name" "-v" "1.0"]))
      "Happy path"))

(deftest lein-project-test
  (is (= {:name "name", :version "1.0", :dependencies [['group/name "1.0"]]}
         (lein-project {:group "group", :name "name",
                        :output ".", :repository nil, :version "1.0"}))
      "Happy path"))

(deftest gemspec-str-test
  (is (= "Gem::Specification.new do |s|\n  s.date = \"2012-08-14\"\n  s.require_paths = [\"lib\"]\n  s.name = \"name\"\n  s.version = \"1.0\"\n  s.homepage = \"https://github.com/bruceadams/java-gem\"\n  s.files = [\"\"]\n  s.authors = [\"unknown\"]\n  s.summary = \"RubyGem wrapper for Java package name\"\n  s.description = \"Autogenerated RubyGem wrapper for group/name-1.0\"\n  s.platform = \"java\"\nend\n"
         (gemspec-str {:group "group", :name "name",
                       :output ".", :repository nil, :version "1.0"}))
      "Not right..."))
