(ns java-gem.core-test
  (:use clojure.test
        java-gem.core))

(deftest gemify-version-test
  (is (= "simpletext" (gemify-version "simpletext")))
  (is (= "1.2.3.dotted" (gemify-version "1.2.3.dotted")))
  (is (= "1.2.3.dashed" (gemify-version "1.2.3-dashed"))))

(deftest parse-args-test
  (is (= {:group "group", :name "name",
          :output ".", :repository nil, :version "1.0"
          :help false :uber-gem false}
         (parse-args ["-g" "group" "-n" "name" "-v" "1.0"]))
      "Happy path"))

;;; FIXME: this should use hard quotes (apostrophes) for Ruby strings
(deftest ruby-const-test
  (is (= "\"abc\"" (ruby-const "abc")))
  (is (= "123" (ruby-const 123)))
  (is (= "[]" (ruby-const [])))
  (is (= "[\"lib\"]" (ruby-const ["lib"])))
  (is (= "[\"lib\", 123]" (ruby-const ["lib", 123])))
  (is (= "[[:a, 1], [:b, \"fred\"]]" (ruby-const {:a 1 :b "fred"}))))

(deftest gemspec-str-test
  (is (re-find #"Gem::Specification\.new do |s|
  s\.date = \"[-0-9]*\"
  s\.require_paths = \[\"lib\"]
  s\.name = \"name\"
  s\.version = \"1\.0\"
  s\.homepage = \"https://github\.com/bruceadams/java-gem\"
  s\.files = \[\"\"]
  s\.authors = \[\"unknown\"]
  s\.summary = \"RubyGem wrapper for Java package name\"
  s\.description = \"Autogenerated RubyGem wrapper for group/name-1\.0\"
  s\.platform = \"java\"
end
"
         (gemspec-str {:group "group", :name "name",
                       :output ".", :repository nil, :version "1.0"}))
      "Not very interesting."))
